"""add b2b_posts

Revision ID: d41e4ea5c2ef
Revises: 3050eb77f254
Create Date: 2026-05-07 14:54:16.935078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd41e4ea5c2ef'
down_revision: Union[str, None] = '3050eb77f254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b2b_posts', sa.Column('shop_id', sa.UUID(), nullable=False))
    op.add_column('b2b_posts', sa.Column('description', sa.String(), nullable=False))
    op.add_column('b2b_posts', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('b2b_posts', sa.Column('category', sa.String(), nullable=False))
    op.alter_column('b2b_posts', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_b2b_posts_id'), 'b2b_posts', ['id'], unique=False)
    op.drop_constraint('b2b_posts_author_id_fkey', 'b2b_posts', type_='foreignkey')
    op.create_foreign_key(None, 'b2b_posts', 'barber_shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('b2b_posts', 'author_id')
    op.drop_column('b2b_posts', 'type')
    op.drop_column('b2b_posts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b2b_posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('b2b_posts', sa.Column('type', postgresql.ENUM('TRADE', 'JOB_LISTING', 'FORUM', name='b2bposttype'), autoincrement=False, nullable=False))
    op.add_column('b2b_posts', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'b2b_posts', type_='foreignkey')
    op.create_foreign_key('b2b_posts_author_id_fkey', 'b2b_posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_b2b_posts_id'), table_name='b2b_posts')
    op.alter_column('b2b_posts', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('b2b_posts', 'category')
    op.drop_column('b2b_posts', 'price')
    op.drop_column('b2b_posts', 'description')
    op.drop_column('b2b_posts', 'shop_id')
    # ### end Alembic commands ###
